In [1]:
install.packages("GDPuc")

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [1]:
library(GDPuc)

Conversion under 1.1 NatCatSERVICE First Option

In [2]:
read_csv= read.csv('/home/insauer/projects/droughts/droughts/data/socio_economic/natcat_current_USD_MER_input_GDPuc.csv')

In [3]:
read_csv

    X   id    iso3c year value
1    0    0   ESP   1980 1500.00
2    1    9   SOM   1980    6.00
3    2   10   MOZ   1980   21.60
4    3   11   GMB   1980   10.50
5    4   12   MLI   1980   25.00
6    5   13   SEN   1980   30.00
7    6   14   BRA   1980  242.00
8    7   15   PHL   1980   41.40
9    8   16   TCD   1980   50.00
10   9   81   LKA   1980    0.60
11  10  158   USA   1980 3000.00
12  11  159   ZAF   1980    5.50
13  12  160   MRT   1980   33.00
14  13  161   NER   1980   50.00
15  14  162   SDN   1980   30.00
16  15  163   SDN   1980   30.00
17  16  166   MEX   1980   16.50
18  17  168   DJI   1980    5.75
19  18  329   PNG   1980   64.80
20  19  360   BFA   1980   66.00
21  20  418   MDG   1981   21.60
22  21  419   AUS   1981   90.00
23  22  420   CUB   1981   59.40
24  23  421   JAM   1981   60.00
25  24  422   BWA   1981   60.50
26  25  455   GIN   1981   66.00
27  26  456   PRT   1981    0.50
28  27  457   MOZ   1981   66.00
29  28  581   HTI   1981  198.00
30  29  617   AGO   1981   20.70
⋮   ⋮   ⋮     ⋮     ⋮    ⋮
890 889 29014 ETH   2016   50.00
891 890 29015 SOM   2016   17.50
892 891 29016 UGA   2016    1.00
893 892 29017 CUB   2016    0.00
894 893 29018 HTI   2016    1.00
895 894 29019 SLV   2016    0.01
896 895 29020 GTM   2016    0.01
897 896 29021 HND   2016    0.01
898 897 29022 PAN   2016    0.01
899 898 29024 COL   2016    0.00
900 899 29025 KHM   2016    0.00
901 900 29076 MMR   2016    0.00
902 901 29134 KEN   2016    0.00
903 902 29138 ECU   2016    0.20
904 903 29232 BOL   2016  450.00
905 904 29477 USA   2016  600.00
906 905 29478 ESP   2016  350.00
907 906 29484 IND   2016  299.00
908 907 29607 CHN   2016 3000.00
909 908 29608 USA   2016  250.00
910 909 29609 USA   2016  150.00
911 910 29617 IDN   2016    1.00
912 911 29618 RUS   2016   17.00
913 912 29776 RUS   2016    0.20
914 913 29777 PER   2016    7.00
915 914 29778 FRA   2016    0.10
916 915 29936 CHN   2016  450.00
917 916 30097 CHN   2016   60.00
918 917 30236 LKA   2016    0.00
919 918 30375 TZA   2016    1.50

In [4]:
converted_2015 <- convertGDP(
    gdp = read_csv,
    unit_in = 'current US$MER',
    unit_out = 'constant 2015 Int$PPP',
    replace_NAs = NA
    )

In [5]:
converted_2015

    X   id    iso3c year value
1    0    0   ESP   1980 4824.3365693
2    1    9   SOM   1980    0.0693829
3    2   10   MOZ   1980           NA
4    3   11   GMB   1980   66.3491530
5    4   12   MLI   1980  125.6304064
6    5   13   SEN   1980   95.9133366
7    6   14   BRA   1980    0.0000000
8    7   15   PHL   1980  241.4130172
9    8   16   TCD   1980  170.7415311
10   9   81   LKA   1980    6.7557883
11  10  158   USA   1980 7434.3810893
12  11  159   ZAF   1980   21.4606521
13  12  160   MRT   1980  206.7341548
14  13  161   NER   1980  182.8024041
15  14  162   SDN   1980  178.8739149
16  15  163   SDN   1980  178.8739149
17  16  166   MEX   1980   85.2233057
18  17  168   DJI   1980           NA
19  18  329   PNG   1980  245.2142257
20  19  360   BFA   1980  193.1859696
21  20  418   MDG   1981   83.6201313
22  21  419   AUS   1981  193.5276845
23  22  420   CUB   1981           NA
24  23  421   JAM   1981  306.4790804
25  24  422   BWA   1981  263.8191333
26  25  455   GIN   1981           NA
27  26  456   PRT   1981    2.5863437
28  27  457   MOZ   1981           NA
29  28  581   HTI   1981 3274.9982109
30  29  617   AGO   1981  185.7969839
⋮   ⋮   ⋮     ⋮     ⋮    ⋮
890 889 29014 ETH   2016 1.230769e+02
891 890 29015 SOM   2016 4.932349e+01
892 891 29016 UGA   2016 2.919554e+00
893 892 29017 CUB   2016           NA
894 893 29018 HTI   2016 2.245980e+00
895 894 29019 SLV   2016 2.036940e-02
896 895 29020 GTM   2016 1.982975e-02
897 896 29021 HND   2016 2.102732e-02
898 897 29022 PAN   2016 1.821108e-02
899 898 29024 COL   2016 0.000000e+00
900 899 29025 KHM   2016 0.000000e+00
901 900 29076 MMR   2016 0.000000e+00
902 901 29134 KEN   2016 0.000000e+00
903 902 29138 ECU   2016 3.544420e-01
904 903 29232 BOL   2016 1.071925e+03
905 904 29477 USA   2016 5.940463e+02
906 905 29478 ESP   2016 4.741437e+02
907 906 29484 IND   2016 1.009906e+03
908 907 29607 CHN   2016 5.078360e+03
909 908 29608 USA   2016 2.475193e+02
910 909 29609 USA   2016 1.485116e+02
911 910 29617 IDN   2016 2.984263e+00
912 911 29618 RUS   2016 4.704164e+01
913 912 29776 RUS   2016 5.534311e-01
914 913 29777 PER   2016 1.337116e+01
915 914 29778 FRA   2016 1.111329e-01
916 915 29936 CHN   2016 7.617540e+02
917 916 30097 CHN   2016 1.015672e+02
918 917 30236 LKA   2016 0.000000e+00
919 918 30375 TZA   2016 3.780191e+00

In [6]:
write.csv(converted_2015, '/home/insauer/projects/droughts/droughts/data/socio_economic/natcat_constant_Int_2015PPP_output_GDPuc.csv')

In [7]:
converted_2017 <- convertGDP(
    gdp = read_csv,
    unit_in = 'current US$MER',
    unit_out = 'constant 2017 Int$PPP',
    replace_NAs = NA
    )

In [8]:
write.csv(converted_2017, '/home/insauer/projects/droughts/droughts/data/socio_economic/natcat_constant_Int_2017PPP_output_GDPuc.csv')

## Conversion under 1.2 NatCatSERVICE Second Option

In [9]:
read_missings=read.csv('/home/insauer/projects/droughts/droughts/data/socio_economic/natcat_constant_2016USD_MER_input_GDPuc.csv')

In [10]:
read_missings

   id    iso3c year value
1    10  MOZ   1980   62.9144563
2   168  DJI   1980   21.1677441
3   420  CUB   1981  156.8362574
4   455  GIN   1981  174.2625082
5   457  MOZ   1981  174.2625082
6  1305  LBR   1983  308.0900588
7  1382  STP   1983   72.2912651
8  1423  ROU   1983   66.2669930
9  1681  DJI   1983   71.4721256
10 1716  TZA   1984   46.9698416
11 2648  HUN   1986 1826.6803680
12 2897  KHM   1987   91.2702676
13 3278  MOZ   1987   45.6351338
14 3555  DJI   1988   14.4300807
15 3674  HRV   1988   55.7919905
16 4141  POL   1989  265.2257433
17 4855  SRB   1990 1836.3198170
18 5268  TWN   1991   69.6657825
19 6053  TWN   1992  140.2617230
20 6054  LTU   1992   85.5334997
21 6756  TWN   1993   17.5737130
22 6758  MNE   1993    0.4484560
23 6759  SRB   1993    0.4650655
24 7100  ERI   1993    8.3047405
25 7216  TWN   1994   16.9221969
26 7458  LTU   1994   64.7792173
27 7515  MDA   1994  194.3376518
28 8126  CUB   1995    0.8661670
29 8462  TWN   1995    0.5121181
30 8698  DJI   1996   28.3477523
⋮  ⋮     ⋮     ⋮    ⋮
45 13120 ERI   2001 8.131237e-01
46 13378 DJI   2001 1.898133e+01
47 13877 TWN   2002 1.121154e+00
48 15482 CUB   2004 1.048062e+03
49 16238 SOM   2005 1.474697e+02
50 18003 SYR   2007 1.231173e+03
51 19246 SOM   2008 0.000000e+00
52 19453 DJI   2008 1.636796e+01
53 19454 ERI   2008 1.337689e+02
54 20079 CUB   2008 1.278920e+02
55 20149 DJI   2009 1.584022e+01
56 20150 ERI   2009 0.000000e+00
57 20152 SOM   2009 0.000000e+00
58 21142 VEN   2009 3.778173e+01
59 21668 DJI   2010 1.545267e+01
60 21670 SOM   2010 0.000000e+00
61 22442 DJI   2011 1.438407e+01
62 22444 SOM   2011 1.664500e+02
63 23150 TKL   2011 3.317592e+01
64 23537 CUB   2012 1.195614e-02
65 23548 SOM   2012 5.226770e+00
66 23978 PRK   2012 5.226770e+01
67 24923 CUB   2013 1.161838e-02
68 26023 PRK   2014 1.013817e+00
69 26365 VEN   2014 1.947297e+02
70 27487 PRK   2015 1.012615e+02
71 27499 VGB   2015 1.518923e-01
72 27634 CUB   2015 5.225592e+01
73 27842 TWN   2015 9.898827e-02
74 29017 CUB   2016 0.000000e+00

In [17]:
converted_2016_2015 <- convertGDP(
    gdp = read_missings,
    unit_in = 'constant 2016 US$MER',
    unit_out = 'constant 2015 Int$PPP',
    replace_NAs = 'linear'
    )

In [18]:
converted_2016_2015

   id    iso3c year value
1    10  MOZ   1980  193.657903
2   168  DJI   1980   36.307005
3   420  CUB   1981          NA
4   455  GIN   1981  467.278140
5   457  MOZ   1981  536.399962
6  1305  LBR   1983  523.848321
7  1382  STP   1983  163.786892
8  1423  ROU   1983  157.629680
9  1681  DJI   1983  122.589293
10 1716  TZA   1984  118.369986
11 2648  HUN   1986 3829.028100
12 2897  KHM   1987  256.459416
13 3278  MOZ   1987  140.470169
14 3555  DJI   1988   24.750536
15 3674  HRV   1988  108.188034
16 4141  POL   1989  591.924702
17 4855  SRB   1990 4939.495148
18 5268  TWN   1991          NA
19 6053  TWN   1992          NA
20 6054  LTU   1992  170.623887
21 6756  TWN   1993          NA
22 6758  MNE   1993    1.071851
23 6759  SRB   1993    1.250974
24 7100  ERI   1993   20.453875
25 7216  TWN   1994          NA
26 7458  LTU   1994  129.222841
27 7515  MDA   1994  672.858089
28 8126  CUB   1995          NA
29 8462  TWN   1995          NA
30 8698  DJI   1996   48.622185
⋮  ⋮     ⋮     ⋮    ⋮
45 13120 ERI   2001   2.002655
46 13378 DJI   2001  32.556862
47 13877 TWN   2002         NA
48 15482 CUB   2004         NA
49 16238 SOM   2005 415.641291
50 18003 SYR   2007         NA
51 19246 SOM   2008   0.000000
52 19453 DJI   2008  28.074391
53 19454 ERI   2008 329.461445
54 20079 CUB   2008         NA
55 20149 DJI   2009  27.169215
56 20150 ERI   2009   0.000000
57 20152 SOM   2009   0.000000
58 21142 VEN   2009  62.117405
59 21668 DJI   2010  26.504486
60 21670 SOM   2010   0.000000
61 22442 DJI   2011  24.671618
62 22444 SOM   2011 469.136821
63 23150 TKL   2011         NA
64 23537 CUB   2012         NA
65 23548 SOM   2012  14.731574
66 23978 PRK   2012         NA
67 24923 CUB   2013         NA
68 26023 PRK   2014         NA
69 26365 VEN   2014 320.157439
70 27487 PRK   2015         NA
71 27499 VGB   2015         NA
72 27634 CUB   2015         NA
73 27842 TWN   2015         NA
74 29017 CUB   2016         NA

In [13]:
write.csv(converted_2016_2015, '/home/insauer/projects/droughts/droughts/data/socio_economic/natcat_missing_constant_Int_2015PPP_output_GDPuc.csv')

In [14]:
converted_2016_2017 <- convertGDP(
    gdp = read_missings,
    unit_in = 'constant 2016 US$MER',
    unit_out = 'constant 2017 Int$PPP',
    replace_NAs = 'linear'
    )

In [15]:
write.csv(converted_2016_2017, '/home/insauer/projects/droughts/droughts/data/socio_economic/natcat_missing_constant_Int_2017PPP_output_GDPuc.csv')

In [16]:
read_emdat= read.csv('/home/insauer/projects/droughts/droughts/data/socio_economic/emdat_current_USD_MER_input_GDPuc.csv')

In [17]:
read_emdat

    X   index iso3c year value
1    0  1213  DJI   1980      NA
2    1  1214  SDN   1980      NA
3    2  1215  SOM   1980      NA
4    3  1216  LKA   1980      NA
5    4  1217  BEN   1983     651
6    5  1218  BFA   1980      NA
7    6  1219  CIV   1983      NA
8    7  1220  CPV   1982      NA
9    8  1221  GHA   1983      NA
10   9  1222  GIN   1981      NA
11  10  1223  GMB   1980      NA
12  11  1224  GNB   1982      NA
13  12  1225  LBR   1983      NA
14  13  1226  MLI   1980      NA
15  14  1227  MRT   1980      NA
16  15  1228  NER   1980      NA
17  16  1229  SEN   1982      NA
18  17  1230  TCD   1981      NA
19  18  1231  TGO   1983      NA
20  19  1232  ZAF   1980      NA
21  20  1233  HTI   1980      NA
22  21  1234  ESP   1980 1500000
23  22  1235  PNG   1980      NA
24  23  1236  PHL   1980      NA
25  24  1337  LKA   1981      NA
26  25  1338  MDG   1981      NA
27  26  1339  MOZ   1981      NA
28  27  1340  DZA   1981      NA
29  28  1341  NGA   1983   71103
30  29  1342  COM   1981      NA
⋮   ⋮   ⋮     ⋮     ⋮    ⋮
642 641 12547 FRA   2022       NA
643 642 12548 GBR   2022       NA
644 643 12549 ITA   2022       NA
645 644 12550 PRT   2022       NA
646 645 12551 UGA   2022       NA
647 646 12552 CHN   2022  7600000
648 647 12553 BFA   2022       NA
649 648 12554 CMR   2022       NA
650 649 12555 CAF   2022       NA
651 650 12556 COD   2022       NA
652 651 12557 MWI   2022       NA
653 652 12558 MLI   2022       NA
654 653 12559 NGA   2022       NA
655 654 12560 SDN   2022       NA
656 655 12561 URY   2022       NA
657 656 12915 HND   2023       NA
658 657 12916 ESP   2023  2400000
659 658 12917 ITA   2023       NA
660 659 12918 IDN   2023       NA
661 660 12919 URY   2023       NA
662 661 12920 BRA   2023  2500000
663 662 12921 BOL   2023       NA
664 663 12922 USA   2023 14500000
665 664 12923 CHN   2023  2700000
666 665 12924 FSM   2023       NA
667 666 13042 COL   2024       NA
668 667 13043 ZMB   2024       NA
669 668 13044 MHL   2024       NA
670 669 13045 MWI   2024       NA
671 670 13046 ZWE   2024       NA

In [18]:
converted_emdat_2015 <- convertGDP(
    gdp = read_emdat,
    unit_in = 'current US$MER',
    unit_out = 'constant 2015 Int$PPP',
    replace_NAs = NA
    )

In [19]:
write.csv(converted_emdat_2015, '/home/insauer/projects/droughts/droughts/data/socio_economic/emdat_constant_Int_2015PPP_output_GDPuc.csv')

In [20]:
converted_emdat_2017 <- convertGDP(
    gdp = read_emdat,
    unit_in = 'current US$MER',
    unit_out = 'constant 2017 Int$PPP',
    replace_NAs = NA
    )

In [21]:
write.csv(converted_emdat_2017, '/home/insauer/projects/droughts/droughts/data/socio_economic/emdat_constant_Int_2017PPP_output_GDPuc.csv')

In [33]:
read_emdat_missings = read.csv('/home/insauer/projects/droughts/droughts/data/socio_economic/emdat_missings_constant2024USD_MER_input_GDPuc.csv')
read_emdat_missings

   X     iso3c year value
1   2010 HUN   1986  1389957
2   2731 HRV   1990  2332050
3   3072 LTU   1992   114874
4   4418 CUB   1998   336463
5   5079 AFG   2000       88
6   6434 CUB   2004     5064
7  12916 ESP   2023  2400000
8  12920 BRA   2023  2500000
9  12922 USA   2023 14500000
10 12923 CHN   2023  2700000

In [34]:
converted_emdat_missings_2023 <- convertGDP(
    gdp = read_emdat_missings,
    unit_in = 'constant 2023 US$MER',
    unit_out = 'constant 2017 Int$PPP',
    replace_NAs = 'linear'
    )

In [35]:
converted_emdat_missings_2023

   X     iso3c year value
1   2010 HUN   1986 2.654866e+06
2   2731 HRV   1990 4.245741e+06
3   3072 LTU   1992 1.765349e+05
4   4418 CUB   1998           NA
5   5079 AFG   2000 3.673149e+02
6   6434 CUB   2004           NA
7  12916 ESP   2023 3.232898e+06
8  12920 BRA   2023 4.309006e+06
9  12922 USA   2023 1.191083e+07
10 12923 CHN   2023 3.773511e+06

In [36]:
write.csv(converted_emdat_missings_2023, '/home/insauer/projects/droughts/droughts/data/socio_economic/emdat_missings_constant_Int_2017PPP_output_GDPuc.csv')

In [37]:
converted_emdat_missings_2015 <- convertGDP(
    gdp = read_emdat_missings,
    unit_in = 'constant 2023 US$MER',
    unit_out = 'constant 2015 Int$PPP',
    replace_NAs = 'linear'
    )

In [38]:
write.csv(converted_emdat_missings_2015, '/home/insauer/projects/droughts/droughts/data/socio_economic/emdat_missings_constant_Int_2015PPP_output_GDPuc.csv')